### ISSUE TITLE
Feature: i18n support for Spanish

### ISSUE THREAD

**Issue by Delavalom** [xavimondev/whatis.dev#4]
Me gustaría que tuviera `i18n` soporte al español para que también desarrolladores en LATAM puedan venir aprender sobre los términos.

Déjame que piensas.

**Comment by xavimondev** [comment]
Buenas! me gusta la idea 💯 , trabajaré en lo que mencionas para muy pronto tener el idioma español.

**Comment by xavimondev** [comment]
He agregado i18n y el idioma por defecto es el español. Para cambiarlos a inglés, hay una opción en el footer.

**Comment by Delavalom** [comment]
> He agregado i18n y el idioma por defecto es el español. Para cambiarlos a inglés, hay una opción en el footer.

Lo probé y quedo buenísimo. Si te parece bien me gustaría agregar términos de vez en cuando, así se va expandiendo el vocabulario del site.

**Comment by xavimondev** [comment]
> > He agregado i18n y el idioma por defecto es el español. Para cambiarlos a inglés, hay una opción en el footer.
> 
> Lo probé y quedo buenísimo. Si te parece bien me gustaría agregar términos de vez en cuando, así se va expandiendo el vocabulario del site.

Hola! muchas gracias y en cuanto agregar más términos, claro que puedes! Solo que ya no será necesario agregar más sugerencias porque con las que aparecen en pantalla son suficientes.
